#Import library classes
from pymap import Coordinates
from pymap import Infobox
from pymap import SVGMap
from pymap import MapData

#Create map from coordinates. The shapefile is located at ne_10m_admin_0_countries and is from Natural Earth Data.
countries = ['Italy','France','Germany','Switzerland','Spain','United Kingdom','Poland','Ukraine','Czechia','Portugal','Ireland','Belgium','Netherlands','Romania','Hungary','Republic of Serbia','Slovakia','Luxembourg','Denmark','Norway','Iceland','Austria','Slovenia','Sweden','Moldova','Bulgaria','Greece','Finland','Belarus','Estonia','Latvia','Lithuania','Albania','Kosovo','Montenegro','Croatia']
myMap = Coordinates('ne_10m_admin_0_countries',3,isl=5,height=600,width=1200,zoom=3,translate=[150,125],countries=countries,res=100)

#Remove spaces
countriesNew = countries.copy()
countriesNew[5] = 'UnitedKingdom'
countriesNew[15] = 'RepublicofSerbia'

#Data sources: IKShPK (Kosovo), Worldometers (others)
cases = [4159122,5877787,3602939,679510,3604799,4450777,2854079,2153864,1652840,842182,255672,1030071,1598164,1072899,798147,706548,387523,69028,266503,119299,6537,637097,249310,1037126,253845,414192,377090,90105,376341,127053,127978,265536,132015,106969,98852,350390]
myData = {'territory_list':countriesNew,'cases':cases,'original':countries}
myData = MapData(myData)
mySVGMap = SVGMap(myData,myMap)

#The cases dataset is used to color the map
mySVGMap['choropleth']['source'] = 'cases'

#Set colors
mySVGMap['choropleth']['colors']['r'] = [0,0]
mySVGMap['choropleth']['colors']['g'] = [0,0]
mySVGMap['choropleth']['colors']['b'] = [0,255]

#Create infobox
mySVGMap['infobox'] = Infobox()

#Line 0
mySVGMap['infobox'].addText('Country: ')
mySVGMap['infobox'].addText('data["data"]["data"]["original"][c]','int')

#Line 1
mySVGMap['infobox'].addText('COVID-19 Cases: ',line=1)
mySVGMap['infobox'].addText('data["data"]["data"]["cases"][c]','int')

#Set inputs
#Also calls Javascript function
#The ONLY place the functions showInfobox() and hideInfobox() are called is below
#They are automatically added to the HTML and Javascript
mySVGMap['inputs']['onHover'] = 'showInfobox([COUNTRY]);'
mySVGMap['inputs']['onMouseOut'] = 'hideInfobox([COUNTRY]);'

#Get javascript code
code = mySVGMap.returnCode()

#Save code
file = open('autogenerated.js','w')
file.write(code)
